export { default as Home } from './Home'
export { default as Events } from './Events'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Gallery } from './Gallery'
export { default as Contact } from './Contact'
